config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'products#index'

  resources :categories, only: [:index, :show]
  resources :products, only: [:show, :new, :edit, :destroy, :create, :update] do
    collection do
      get 'search'
    end
    resources :comments, only: :create
    get "/buy" , to: "creditcards#buy"

    resource :favorites, only: [:create, :destroy]
    get :favorites, on: :collection

    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category_list', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :users, only: [:index, :show] do
    resources :creditcards, only: [:index, :new, :create, :destroy]
    resources :favorites, :index
  end
  
  get '/logout', to: 'users#logout'

end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping
  belongs_to_active_hash :day

  belongs_to :user, optional: true
  validates :first_name, :last_name,
            presence: true,
            length: { maximum: 255 },
            format: { with: /\A[一-龥]+\z/ }

  validates :first_name_kana, :last_name_kana,
            presence: true,
            length: { maximum: 255 },
            format: { with: /\A[ぁ-んー－]+\z/ }

  validates :zip1, 
            presence: true,
            length: { maximum: 3 }
  
  validates :zip2,
            presence: true,
            length: { maximum: 4 }
  
  validates :address1, :address2,
            presence: true,
            length: { maximum: 255 },
            format: { with: /\A[ぁ-んァ-ン一-龥]/ }

  validates :street_address,
            presence: true,
            length: { maximum: 255 }

  validates :apartment,
            length: { maximum: 255 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :product
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user

  validates :payjp_id, presence: true
  validates :user_id, presence: true
  
end

app/models/day.rb
class Day < ActiveHash::Base
  include ActiveHash::Associations
  belongs_to :address
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
  
  validates :user_id, uniqueness: { scope: :product_id }

  def favorite_by?(product)
    Favorite.where(product_id: product.id).exists?
  end

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImagesUploader
  belongs_to :product, optional: true
  validates :image, presence: true

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  include ActiveHash::Associations
  belongs_to :address
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :status, presence: true
  validates :postage_bearer, presence: true
  validates :shipping_area, presence: true
  validates :shipping_day, presence: true
  validates :price, presence: true, inclusion: 300..9999999
  validates :category_id, presence: true
  validates :user_id, presence: true
  validates :condition, presence: true

  def favorite_by?(product)
    Favorite.where(product_id: product.id).exists?
  end

  def self.search(search)
    return Product.all unless search
    Product.where('name LIKE(?)', "%#{search}%")
  end

end

app/models/shipping.rb
class Shipping < ActiveHash::Base
  include ActiveHash::Associations
  belongs_to :address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_product, through: :favorites, source: :product
  has_many :comments
  has_many :creditcards
  has_one :address
  
  validates :nickname,
            presence: true,
            uniqueness: true,
            length: { maximum: 255 }
            
  validates :first_name, :last_name,
            presence: true,
            length: { maximum: 255 },
            format: { with: /\A[一-龥]+\z/ }

  validates :first_name_kana, :last_name_kana,
            presence: true,
            length: { maximum: 255 },
            format: { with: /\A[ぁ-んー－]+\z/ }

  validates :birthday, 
            presence: true

  validates :tel, 
            presence: true,
            format: { with: /\A\d{10}$|^\d{11}\z/ }

  validates :password,
            presence: true, 
            length: { minimum: 7 }

  validates :email,
            length: { maximum: 255 }, 
            format: { with: /\A[\x21-\x3f\x41-\x7e]+@(?:[-a-z0-9]+\.)+[a-z]{2,}\z/i },
            uniqueness: true

  def own_product?(product)
    self.id == product.user_id
  end

  def favorite_by?(product)
    Favorite.where(product_id: product.id).exists?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_messages
    return "" if resource.errors.empty?
    html = ""
    # エラーメッセージ用のHTMLを生成
    messages = resource.errors.full_messages.each do |msg|
      html += <<-EOF
        <div class="error_field alert alert-danger" role="alert">
          <p class="error_msg">#{msg}</p>
        </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if @address.errors.empty?

    html = ""
    messages = @address.errors.full_messages.each do |msg|
      html += <<-EOF
      <div class="error_field alert alert-danger" role="alert">
        <p class="error_msg">#{msg}</p>
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.haml
%h1 Items#index
%p Find me in app/views/items/index.html.erb
test2020/03/1９ 1218

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample71c
    = include_gon
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{href: "https://use.fontawesome.com/releases/v5.6.1/css/all.css", rel: "stylesheet"}/
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css", rel: "stylesheet"}/
    -# 画像を拡大表示させる記述以下２行
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js", type: "text/javascript"}

  %body
    = yield

app/views/shared/_exhibit-btn.html.haml
-# ログインしているなら出品ボタン表示
- if user_signed_in?
  = link_to new_product_path, class:'top-exhibit__link' do
    .top-exhibit
      .top-exhibit__link--text 出品する
      = image_tag "icon_camera.png"
- else
  = link_to new_user_session_path, class:'top-exhibit__link' do
    .top-exhibit
      .top-exhibit__link--text 出品する
      = image_tag "icon_camera.png"

app/views/shared/_footer.html.haml
/-- footer上部 --/
.top-guidance
  .top-guidance__title
    %h2
      だれでもかんたん、人生を変えるフリマアプリ
  .top-guidance__download
    %p
      今すぐ無料ダウンロード！
  .top-icon
    /-- App Storeのロゴ --/
    = link_to "https://apps.apple.com/jp/app/%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA-%E3%83%95%E3%83%AA%E3%83%9E%E3%82%A2%E3%83%97%E3%83%AA-%E3%82%B9%E3%83%9E%E3%83%9B%E6%B1%BA%E6%B8%88%E3%83%A1%E3%83%AB%E3%83%9A%E3%82%A4/id667861049" do
      = image_tag ("apple.png"), class: "apple"
    /-- Google Playのロゴ --/
    = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari" do
      = image_tag ("google.png"), class: "google"

%footer
  /-- footerのリンク --/
  .footer__container
    %ul.top-contents
      %li.top-content
        %h2.top-content__head
          FURIMAについて
        /-- aタグをホバー中、下線部が表示されないバグが残ってる --/
        %ul.top-underline
          %li
            = link_to "会社概要（運営会社）", "https://apps.apple.com/jp/app/%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA-%E3%83%95%E3%83%AA%E3%83%9E%E3%82%A2%E3%83%97%E3%83%AA-%E3%82%B9%E3%83%9E%E3%83%9B%E6%B1%BA%E6%B8%88%E3%83%A1%E3%83%AB%E3%83%9A%E3%82%A4/id667861049"
          %li
            = link_to "プライバシーポリシー", "#"
          %li
            = link_to "FURIMA利用規約", "#"
          %li
            = link_to "ポイントに関する特約", "#"
      %li.top-content
        %h2.top-content__head
          FURIMAを見る
        %ul.top-underline
          %li
            = link_to "カテゴリー一覧", categories_path
          %li
            = link_to "ブランド一覧", "#"
      %li.top-content
        %h2.top-content__head
          ヘルプ＆ガイド
        %ul.top-underline
          %li
            = link_to "FURIMAガイド", "#"
          %li
            = link_to "FURIMAロゴ利用ガイドライン", "#"
          %li
            = link_to "お知らせ", "#"
    /-- FURIMAのロゴ --/
    .top-logo
      =link_to root_path do
        = image_tag "logo-white.png", size: "140x50"
      %p © FURIMA

app/views/shared/_header.html.haml
%header.top-header
  .top-header--top
    = link_to root_path do
      = image_tag "logo.png", class: "top-header--top__image"
    -# 検索フォーム
    = form_with(url: search_products_path, local: true, method: :get, class: "search-form") do |form|
      .top-header--top__search
        = form.text_field :keyword, placeholder: "キーワードから探す", class: "top-form"
        = form.submit "", class: "top-search" 
        %i.fas.fa-search
  .top-header--middle
    .top-header--middle__left
      -# カテゴリーから探す
      %ul.top-category
        %li.top-category--left
          = link_to categories_path do
            カテゴリーから探す
          %ul.top-category__ul
            - @categories.each do |category|
              %li.top-category__ul__li
                = link_to category_path(category) do
                  = category.name
                  %ul.top-category__children
                    - category.children.each do |child|
                      %li.top-category__children__li
                        = link_to category_path(child) do
                          = child.name
                          %ul.top-category__grandchild
                            - child.children.each do |grandchild|
                              .top-category__grandchild__li
                                =link_to category_path(grandchild) do
                                  = grandchild.name

      -# ブランドから探す
    .top-category--right ブランドから探す
    .top-header--middle__right
      -# 会員登録ボタン
      - if user_signed_in?
        .top-category__btn--sign_in
          = link_to "#", class: "top-li_to" do
            %i.far.fa-bell
            %p.top-li お知らせ
        .top-category__btn--sign_in
          = link_to "#", class: "top-li_to" do
            %i.fas.fa-check
            %p.top-li やることリスト
        .top-category__btn--sign_in
          = link_to user_path(current_user.id), class: "top-li_to" do
            = image_tag "komaki.jpg"
            %p.top-li マイページ 
      - else
        .top-category__btn--left.btn 
          = link_to "新規会員登録", "/users"
        -# ログインボタン
        .top-category__btn--right
          = link_to "ログイン", "/users/sign_in"

app/views/shared/_product_footer.html.haml
.exhibit-footer
  .exhibit-footer--container
    .exhibit-footer--container__menu
      = link_to "プライバシーポリシー", "#"
      = link_to "FURIMA利用規約", "#"
      = link_to "特定商取引に関する表記", "#"
    .exhibit-footer--container__logo
      =link_to root_path do
        = image_tag "logo.png", size: "120x30"
      %p © FURIMA

app/views/shared/_product_header.html.haml
-# ロゴ
.exhibit-header
  = link_to root_path do
    = image_tag "logo.png", class: "exhibit-header--logo",size: "180x50"

app/views/shared/_user_side-bar.html.haml
-# ユーザーサイドバー
.myp-side-bar
  %ul.myp-container
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "マイページ", user_path(current_user.id)
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "お知らせ", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "やることリスト", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "いいね！一覧", user_favorites_path(current_user)
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "出品する", new_product_path
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "下書き一覧", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "出品した商品 - 出品中", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "出品した商品 - 取引中", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "出品した商品 - 売却済み", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "購入した商品 - 取引中", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "購入した商品 - 過去の取引", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "ニュース一覧", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "評価一覧", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "ガイド", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "お問い合わせ", "#"
      %i.fas.fa-chevron-right

  %h1 フリマペイ
  %ul.myp-container
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "売上・振込申請", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "ポイント", "#"
      %i.fas.fa-chevron-right

  %h1 設定
  %ul.myp-container
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "プロフィール", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "発送元・お届け先住所変更", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "支払い方法", user_creditcards_path(current_user.id)
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "メール/パスワード", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "本人情報", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left 
        = link_to "電話番号の確認", "#"
      %i.fas.fa-chevron-right
    %li.myp-container__box
      .myp-container__box--left
        = link_to "ログアウト", logout_path
      %i.fas.fa-chevron-right