config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'products#index'

  resources :categories, only: [:index, :show]
  resources :products, only: [:show, :new, :edit, :destroy, :create, :update] do
    collection do
      get 'search'
    end
    resources :comments, only: :create
    get "/buy" , to: "creditcards#buy"

    resource :favorites, only: [:create, :destroy]
    get :favorites, on: :collection

    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category_list', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :users, only: [:index, :show] do
    resources :creditcards, only: [:index, :new, :create, :destroy]
    resources :favorites, :index
  end
  
  get '/logout', to: 'users#logout'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :status, presence: true
  validates :postage_bearer, presence: true
  validates :shipping_area, presence: true
  validates :shipping_day, presence: true
  validates :price, presence: true, inclusion: 300..9999999
  validates :category_id, presence: true
  validates :user_id, presence: true
  validates :condition, presence: true

  def favorite_by?(product)
    Favorite.where(product_id: product.id).exists?
  end

  def self.search(search)
    return Product.all unless search
    Product.where('name LIKE(?)', "%#{search}%")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login, except: [:index, :show, :search]
  MAX_DISPLAY_RELATED_PRODUCTS = 3
  before_action :user_to_current_user?, only: [:edit, :update]
  

  def index
    # @products = Product.includes(:images,:user).order('created_at DESC')
    # ↓新規投稿商品。新しく作成された3つのデータのみ取得。
    @products = Product.where(condition: 1).order(created_at: "DESC").take(MAX_DISPLAY_RELATED_PRODUCTS)
    # ↓1(出品中)のブランド名「ma--ru」の商品をshuffleメソッドとtakeメソッドでランダムで３つのデータを取得。distinctで重複する情報削除。
    @products_B = Product.where(condition:1, brand:'ma--ru').distinct.shuffle.take(MAX_DISPLAY_RELATED_PRODUCTS)
    
    # ↓メンズ商品。(出品中)かつカテゴリ「メンズ」の商品を３つのデータを取得。
    @mens_array = []
    @category = Category.find_by(name: "メンズ")
    @category.children.each do |child|
      child.children.each do |grand_child|
        # 空の配列にカテゴリ：メンズの孫IDと出品中IDのproductを格納
        @mens_array << Product.where(category_id: grand_child[:id],condition: 1)
      end
    end
    # 格納した配列をフラットにして、ランダムで3つ取り出す。
    @mens_flat = @mens_array.flatten
    @mens_samle = @mens_flat.sample(3)

    # ↓レディース商品。(出品中)かつカテゴリ「メンズ」の商品を３つのデータを取得。
    @ledies_array = []
    @category = Category.find_by(name: "レディース")
    @category.children.each do |child|
      child.children.each do |grand_child|
        # 空の配列にカテゴリ：メンズの孫IDと出品中IDのproductを格納
        @ledies_array << Product.where(category_id: grand_child[:id],condition: 1)
      end
    end
    # 格納した配列をフラットにして、ランダムで3つ取り出す。
    @ledies_flat = @ledies_array.flatten
    @ledies_samle = @ledies_flat.sample(3)
  end

  def new
    @product = Product.new
    @product.images.new
    @category_parent_array = ["---"]
    
    # データベースから、親カテゴリーのみ抽出し、配列化
    array = Category.where(ancestry: nil).pluck(:name)
    @category_parent_array.push(array)
    @category_parent_array.flatten!

    def get_category_children
      # 選択された親カテゴリーに紐付く子カテゴリーの配列を取得
      @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
    end
      # 子カテゴリーが選択された後に動くアクション
    def get_category_grandchildren
      # 選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
      @category_grandchildren = Category.find("#{params[:child_id]}").children
    end
  end


  def create
    @product = Product.new(product_params)
    category_id_params
    if @product.save
      params[:images][:image].first(10).each do |a|
        @images = @product.images.create!(image: a, product_id: @product.id)
      end
      redirect_to root_path
    else
      redirect_to new_product_path unless @product.valid?
    end
  end

  def show
    # 商品が削除されているなら
    unless Product.where(id: params[:id]) == []
      @product = Product.find(params[:id])
      @comment = Comment.new
      @comments = @product.comments.includes(:user)
      @image   = Image.where(product_id: @product)
    else
      redirect_to root_path
    end
  end


  def edit
    # 編集する商品を選択
    @parents = Category.where(ancestry:nil)
    @category = Category.find(@product[:category_id])
    
    # カテゴリーの情報
    @category_root = [@category.root.name]
    @category_parent = [@category.parent.name]
    @category_my = [@category.name, @category.id]

    # データベースから、親カテゴリーのみ抽出し、配列化
    def category_list
      @categories = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).siblings
    end
    # 選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    def get_category_children
      @category_children = Category.find(params[:parent_id]).children
    end
    # 子カテゴリーが選択された後に動くアクション
    def get_category_grandchildren
      #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
      @category_grandchildren = Category.find("#{params[:child_id]}").children
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(params[:id])
    else
      redirect_to edit_product_path(@product)
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  def favorites
    @products_favo = current_user.favorite_products.includes(:user).recent
  end
  
  def search
    @products = Product.search(params[:keyword])
  end
  
  private
  def product_params
    params.require(:product).permit(:name, :description, :brand, :status, :postage_bearer, :shipping_area, :shipping_day, :price, :size, :category_id, :condition ,images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def category_id_params
    category = params.permit(:category_id)
    @product[:category_id] = category[:category_id]
  end

  def user_to_current_user?
    @product = Product.find(params[:id])
    if ! user_signed_in? || current_user.id != @product.user_id 
      redirect_to action: :index 
    end
  end


  private
  def require_login
    unless user_signed_in?
      flash[:error] = "ログイン状態でありません"
      redirect_to root_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_favorite.html.haml
= link_to product_favorites_path(@product), method: :delete, remote: true, id: :"js-favorite-button-for-product-#{@product.id}", :class => "change" do
  %i.fas.fa-star
  %p お気に入り

app/views/products/_favorite_area.html.haml
- if product.favorite_by?
  = render 'products/favorite', product: product
- else
  = render 'products/unfavorite', product: product

app/views/products/_product.html.haml
.product-show-btns__like__star#favo
  = render 'products/favorite_area', product: product

app/views/products/_unfavorite.html.haml
= link_to product_favorites_path(@product), method: :post, remote: true, id: :"js-favorite-button-for-product-#{@product.id}", :class => "changed" do
  %i.fas.fa-star
  %p お気に入り

app/views/products/edit.html.haml
-# ヘッダー
= render 'shared/product_header'

-# 出品情報
.exhibit-boby
  .exhibit-boby--container
    = form_with model: @product, class:"form-box", local: true do |f| 
      .exhibit-boby--container__image
        .exhibit-flame
          .exhibit-label
            %p 出品画像
            %p.need 必須
          %p 最大10枚までアップロードできます

          -# 画像編集
          #image-box
            #previews
              .preview
                - if @product.persisted?
                  - @product.images.each_with_index do |image, i|
                    .image_box
                      = image_tag image.image.url, data: { index: i }, width: "114", height: '80'
                      .js_remove__btn(data-index="#{i}")
                        = "削除"
                %label#image-box__container
                  %i.fa.fa-camera
                  %p クリックしてアップロード
            = f.fields_for :images do |image|
              .js-file_group(data-index = "#{image.index}")
                = image.file_field :image, class: 'js-file hidden'
                .js-remove.hidden(data-index = "#{image.index}") 削除#{image.index}
              - if @product.persisted?
                = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
            - if @product.persisted?
              .js-file_group(data-index = "#{@product.images.count}")
                = file_field_tag :image, name: "product[images_attributes][#{@product.images.count}][image]", class: 'js-file hidden'
                .js-remove.hidden(data-index = "#{@product.images.count}") 削除

      -# 商品情報編集
      .exhibit-boby--container__name
        .exhibit-flame
          .exhibit-label
            %p 商品名
            %p.need 必須
          = f.text_field :name, placeholder: '40文字まで'
          .exhibit-label
            %p 商品の説明
            %p.need 必須
          = f.text_area :description, class: "exhibit-text", placeholder: '商品の説明（必須1000文字以内)&#13;&#10;(色、素材、重さ、定価、注意点など)&#13;&#10; &#13;&#10;例)2010年頃に１万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでオススメです♡'.html_safe
          %h5.exhibit-text__length 
      .exhibit-boby--container__detail
        .exhibit-flame
          %h3.exhibit_h3 商品の詳細

          -# カテゴリー編集
          .exhibit-label
            .exhibit-detail-categories
              .exhibit-detail-category-name
                = f.label 'カテゴリー', class: 'exhibit-default--label'
                %p.need 必須
              .exhibit-select-wrapper
                .exhibit-select-wrapper__box{id: "category-reset-js"}
                  = f.select :category, @category_root, {}, {class: 'exhibit-category-select', id: 'parent_categories'}
              .exhibit-select-wrapper__added{ id: "children_wrapper" }
                .exhibit-select-wrapper__box
                  = f.select :category, @category_parent, {}, class: "exhibit-select-wrapper__box--select", id: 'child_categories'
              .exhibit-select-wrapper__added{ id: "grandchildren_wrapper" }
                .exhibit-select-wrapper__box
                  = f.select :category_id, [@category_my], {}, class: "exhibit-select-wrapper__box--select", id: 'grandchild_categories'

          -# ブランド編集
          .exhibit-label
            %p ブランド
            %p.any 任意
          = f.text_field :brand, placeholder: '例）シャネル'
          -# 商品の状態-編集
          .exhibit-label
            %p 商品の状態
            %p.need 必須
          = f.select :status, [["選択してください",""],["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]]
      -# 配送料の負担-編集
      .exhibit-boby--container__delivery
        .exhibit-flame
          %h3.exhibit_h3 配送について
          .exhibit-label
            %p 配送料の負担
            %p.need 必須
          = f.collection_select :postage_bearer, Shipping.all, :id, :name, prompt: "選択してください"
          -# 発送元の地域-編集
          .exhibit-label
            %p 発送元の地域
            %p.need 必須
          = f.collection_select :shipping_area, Prefecture.all, :id, :name, prompt: "選択してください"
          -# 発送までの日数-編集
          .exhibit-label
            %p 発送までの日数
            %p.need 必須
          = f.collection_select :shipping_day, Day.all, :id, :name, prompt: "選択してください"
      -# 販売価格-編集
      .exhibit-boby--container__price
        .exhibit-flame
          %h3.exhibit_h3 販売価格（300~9,999,999）
          .exhibit-price
            .exhibit-price__flame
              .exhibit-price__flame--label
                %p 販売価格
                %p.need 必須
              %p ¥
            = f.text_field :price, placeholder: '0', id: "exhibit-price", style: "text-align: right;"
          .exhibit-commission
            %p 販売手数料（10%）
            %p#tax-price ー
          .exhibit-profit
            %p  販売利益
            %p#profit-price ー
          .exhibit-hidden
            = f.hidden_field :condition, value: 1
          -# ボタン
          .exhibit-btn
            = f.submit "変更する",class:"exhibit-submit"
            = link_to product_path(@product), class: "" do
              もどる
          %p
            禁止されている出品、
            %a{href:"#"}>行為
            および
            %a{href:"#"}>出品物
            を必ずご確認ください。
            %a{href:"#"}>偽ブランド品
            や
            %a{href:"#"}>盗難品
            などの販売は犯罪であり、法律により処罰される可能性があります。また、出品をもちまして
            %a{href:"#"}>加盟店規約
            に同意したことになります。
            
-# フッター
= render 'shared/product_footer'

app/views/products/index.html.haml
-# ヘッダー
= render 'shared/header'
-# 商品出品ボタン
= render 'shared/exhibit-btn'

-# トップページ
.top-main
  .top-main__view
    .top-main__view__container
      .top-main__view__title 人生を変えるフリマアプリ
      .top-main__view__text FURIMAはだれでもかんたんに出品・購入できる<br>フリマアプリです
      -# アップルストアボタン
      = link_to "https://apps.apple.com/jp/app/%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA-%E3%83%95%E3%83%AA%E3%83%9E%E3%82%A2%E3%83%97%E3%83%AA-%E3%82%B9%E3%83%9E%E3%83%9B%E6%B1%BA%E6%B8%88%E3%83%A1%E3%83%AB%E3%83%9A%E3%82%A4/id667861049" do
        = image_tag "apple.png", class: "company-btn"
        %span<>
      -# グーグルボタン
      = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari" do
        = image_tag "google.png", class: "company-btn google"
.top-title
  .top-title__text FURIMAが選ばれる3つの理由
  .top-title__images
    .top-title__images--left.reason
      %span.span 1
      = image_tag "pict-reason-01.jpg", class: "reason-size"
      %h1 
        %span> 3分
        &nbsp;ですぐに出品
      %p スマホで入力するだけで簡単に出品できる！
    .top-title__images--center.reason
      %span.span 2
      = image_tag "pict-reason-02.jpg", class: "reason-size"
      %h1 
        %span> シンプル 
        &nbsp;で使いやすい
      %P めんどくさい入力は必要なく、検索も購入もスムーズ！
    .top-title__images--right.reason
      %span.span 3
      = image_tag "pict-reason-03.jpg", class: "reason-size"
      %h1
        %span> 手数料 
        &nbsp;業界最安
      %P 最大3%でお得に出品&購入！
.member
  .member__container
    %h1 会員数日本一位
    %p FURIMAは、フリマアプリで最も人気。<br>出品・購入回数も業界最多です！<br>ほしかったあの商品に出会えるかもしれません。
    = link_to "https://apps.apple.com/jp/app/%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA-%E3%83%95%E3%83%AA%E3%83%9E%E3%82%A2%E3%83%97%E3%83%AA-%E3%82%B9%E3%83%9E%E3%83%9B%E6%B1%BA%E6%B8%88%E3%83%A1%E3%83%AB%E3%83%9A%E3%82%A4/id667861049" do
      = image_tag "apple.png", class: "company-btn"
      %span<>
    = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari" do
      = image_tag "google.png", class: "company-btn google"
.top-char
  .top-char__container
    %h1 FURIMAの特徴
    .top-illust
      .top-illust--left.illust-padding
        = image_tag "icon-01.png", class: "illust-size"
        %h2 簡単に売り買いできる
        %p スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .top-illust--center.illust-padding
        = image_tag "icon-03.png", class: "illust-size"
        %h2 売上金は即日振込みに対応
        %p 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .top-illust--right.illust-padding
        = image_tag "icon-04.png", class: "illust-size"
        %h2 様々な支払いに対応
        %p お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
-# ピックアップ商品一覧
.top-picup
  .top-picup__container
    %h1 ピックアップNEW!!
    %h2 新規投稿商品
    .top-picup__item
      - @products.each do |product|
        = link_to product_path(product) do
          .picup-size
            .product-box
              - product.images.first(1).each do |i|
                = image_tag i.image.url
              .top-product__message
                %ul
                  %li 
                    = product.name
                  %li.top-flex
                    .top-flex--left
                      %p 
                        = product.price
                      %p 円
                    .top-flex--right 
                %p (税込)
  -# メンズピック商品一覧
  .top-picup__container
    %h1.top-picup__space ピックアップカテゴリー
    %h2 メンズ
    .top-picup__item
      - @mens_samle.each do |product|
        = link_to product_path(product) do
          .top-picup__item--left.picup-size
            .product-box
              - product.images.first(1).each do |i|
                = image_tag i.image.url
              .top-product__message
                %ul
                  %li 
                    = product.name
                  %li.top-flex
                    .top-flex--left
                      %p 
                        = product.price
                      %p 円
                    .top-flex--right 
                %p (税込)
    -# レディースピック商品一覧
    .top-picup__container
      %h2 レディース
      .top-picup__item
        - @ledies_samle.each do |product|
          = link_to product_path(product) do
            .top-picup__item--left.picup-size
              .product-box
                - product.images.first(1).each do |i|
                  = image_tag i.image.url
                .top-product__message
                  %ul
                    %li 
                      = product.name
                    %li.top-flex
                      .top-flex--left
                        %p 
                          = product.price
                        %p 円
                      .top-flex--right 
                  %p (税込)

-# フッター
= render 'shared/footer'

app/views/products/new.html.haml
-# ヘッダー
= render 'shared/product_header'

-# 画像投稿
.exhibit-boby
  .exhibit-boby--container
    = form_with model: @product, class:"form-box", local: true do |f| 
      .exhibit-boby--container__image
        .exhibit-flame
          .exhibit-label
            %p 出品画像
            %p.need 必須
          %p 最大10枚までアップロードできます
          = f.fields_for :images do |i|
            #image-box-1
              %label#image-box__container.item-num-0
                = i.file_field :image, multiple: true, class: "exhibit-image__area", type: 'file', name: "images[image][]", value:"",  id:"img-file"
                %i.fa.fa-camera
                %p クリックしてアップロード
      -# 商品名 & 商品説明
      .exhibit-boby--container__name
        .exhibit-flame
          .exhibit-label
            %p 商品名
            %p.need 必須
          = f.text_field :name, placeholder: '40文字まで'
          .exhibit-label
            %p 商品の説明
            %p.need 必須
          = f.text_area :description, class: "exhibit-text", placeholder: '商品の説明（必須1000文字以内)&#13;&#10;(色、素材、重さ、定価、注意点など)&#13;&#10; &#13;&#10;例)2010年頃に１万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでオススメです♡'.html_safe
          %h5.exhibit-text__length 
      -# カテゴリー選択
      .exhibit-boby--container__detail
        .exhibit-flame
          %h3.exhibit_h3 商品の詳細
          .exhibit-label
            .exhibit-detail-category
              .exhibit-detail-category-name
                = f.label 'カテゴリー', class: 'exhibit-default--label'
                %p.need 必須
              .exhibit-select-wrapper
                .exhibit-select-wrapper__box
                  = f.select :category, @category_parent_array, {}, {class: 'exhibit-category-select', id: 'parent_category'}
          -# ブランドと商品状態
          .exhibit-label
            %p ブランド
            %p.any 任意
          = f.text_field :brand, placeholder: '例）シャネル'
          .exhibit-label
            %p 商品の状態
            %p.need 必須
          = f.select :status, [["選択してください",""],["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]]
      -# 配送関係
      .exhibit-boby--container__delivery
        .exhibit-flame
          %h3.exhibit_h3 配送について
          .exhibit-label
            %p 配送料の負担
            %p.need 必須
          = f.collection_select :postage_bearer, Shipping.all, :id, :name, prompt: "選択してください"
          .exhibit-label
            %p 発送元の地域
            %p.need 必須
          = f.collection_select :shipping_area, Prefecture.all, :id, :name, prompt: "選択してください"
          .exhibit-label
            %p 発送までの日数
            %p.need 必須
          = f.collection_select :shipping_day, Day.all, :id, :name, prompt: "選択してください"
      -# 販売価格
      .exhibit-boby--container__price
        .exhibit-flame
          %h3.exhibit_h3 販売価格（300~9,999,999）
          .exhibit-price
            .exhibit-price__flame
              .exhibit-price__flame--label
                %p 販売価格
                %p.need 必須
              %p ¥
            = f.text_field :price, placeholder: '0', id: "exhibit-price", style: "text-align: right;"
          .exhibit-commission
            %p 販売手数料（10%）
            %p#tax-price ー
          .exhibit-profit
            %p  販売利益
            %p#profit-price ー
          .exhibit-hidden
            = f.hidden_field :condition, value: 1
          -# ボタン
          .exhibit-btn
            = f.submit "出品する",class:"exhibit-submit"
            = f.submit "下書きに保存",class:"exhibit-draft"
            = link_to "もどる", root_path,class: ""
          %p
            禁止されている出品、
            %a{href:"#"}>行為
            および
            %a{href:"#"}>出品物
            を必ずご確認ください。
            %a{href:"#"}>偽ブランド品
            や
            %a{href:"#"}>盗難品
            などの販売は犯罪であり、法律により処罰される可能性があります。また、出品をもちまして
            %a{href:"#"}>加盟店規約
            に同意したことになります。

-# フッター
= render 'shared/product_footer'

app/views/products/search.html.haml
= render 'shared/header'
.search-title
  = params[:keyword] + "の検索結果"
.search-flex
  - @products.each do |product|
    .c-show__box__image.search-size
      - if product.condition == 3
        .product-sold-container__search
          %p sold
      = link_to product_path(product) do
        - product.images.first(1).each do |image|
          = image_tag image.image.url
        .c-show__box__text
          %ul
            %li 
            = product.name
            %li 
            = product.price 
            円
          %p (税込)
= render 'shared/footer'

app/views/products/show.html.haml
-# ヘッダー
= render 'shared/header'

-# パンくず
-# logout.html.hamlと同じclass
.myp-header
  %ul.myp-header__container
    %li
      = link_to root_path do
        FURIMA
      %i.fas.fa-chevron-right
    %li
      = link_to category_path(@product.category.root) do
        = @product.category.root.name
      %i.fas.fa-chevron-right
    %li
      = link_to category_path(@product.category.parent) do
        = @product.category.parent.name
      %i.fas.fa-chevron-right
    %li
      = link_to category_path(@product.category) do
        = @product.category.name
      %i.fas.fa-chevron-right
    %li
      = @product.name

-# 出品ボタン
= render 'shared/exhibit-btn'

-# 商品情報
.product-show
  .product-show-main
    .product-show-box
      -# 商品名
      .product-show-items
        %h2.puroduct-name
          = @product.name
        -# 1枚目の画像を大きく
        .product-show-item-lists
          %ul.product-show-item-lists__img
            %li.product-show-item-lists__img--main{ id: "main" }
              %a{class: "data-lightbox", data: { lightbox: "group"} , href: @image.first.image.url}
                = image_tag @image.first.image.url, class: "main-size"

              // 以下３行でsold表示
              - if @product.condition == 3
                .product-sold-container
                  %p sold
              -# 商品の画像一覧
              %ul.product-show-item-lists__sub
                - @image.each do |image|
                  %li.product-show-item-lists__sub--img{ id: "first" }
                    = image_tag image.image.url, class: "sub-size"
      -# 商品の値段
      .product-show-price
        %span.product-show-price__span1
          ¥
          = @product.price
        .product-show-price__tax
          %span.product-show-span2
            (税込) 
            %span.product-show-span3
              送料込み
      -# 商品説明
      .product-show-content
        .product-show-content__title
          出品説明
        .product-show-content__text
          = simple_format(@product.description)

      -# 商品情報の内容
      .product-show-status
        %table.show-teable
          %tr.show-teable__tr
            %th.show-teable__th 出品者
            %td.show-teable__td
              = @product.user.nickname
          %tr.show-teable__tr
            %th.show-teable__th カテゴリー
            %td.show-teable__td 
              %p
                = @product.category.root.name
                %br
                = @product.category.parent.name
                %br
                = @product.category.name
          %tr.show-teable__tr
            %th.show-teable__th ブランド
            %td.show-teable__td
              = @product.brand
          %tr.show-teable__tr
            %th.show-teable__th 商品のサイズ
            %td.show-teable__td 
              = @product.size
          %tr.show-teable__tr
            %th.show-teable__th 商品の状態
            %td.show-teable__td
              = @product.status
          %tr.show-teable__tr
            %th.show-teable__th 配送料の負担	
            %td.show-teable__td 
              = @product.postage_bearer
          %tr.show-teable__tr
            %th.show-teable__th 発送元の地域
            %td.show-teable__td
              = @product.shipping_area
          %tr.show-teable__tr
            %th.show-teable__th 発送日の目安
            %td.show-teable__td
              = @product.shipping_day

      - if user_signed_in?
        - if @product.user_id != current_user.id
          .product-show-btns
            .product-show-btns__like#changed-color
              .product-show-btns__like__star#favo
                - if Favorite.find_by(user_id: current_user.id, product_id: @product.id)
                  = render 'products/favorite', product: @product
                - else
                  = render 'products/unfavorite', product: @product
            .product-show-btns__report
              %i.fas.fa-flag
              %p 不適切な商品の情報
        - else
          .product-show-btns
            .product-show-btns__like
              %i.fas.fa-star
              %p お気に入り
            .product-show-btns__report
              %i.fas.fa-flag
              %p 不適切な商品の情報

      - if user_signed_in?
        - if @product.user_id == current_user.id
          .product-show-link
            .product-show-link__edit
              = link_to edit_product_path(@product) do
                編集
            .product-show-link__destroy
              = link_to product_path(@product), method: :delete do
                削除
        - else
          - if @product.condition == 1
            .product-show-link
              .product-show-link__btn
                = link_to product_buy_path(@product) do
                  購入する
    -# コメント欄
    .product-comments-box
      .product-comments
        %h2.product-comments__header コ  メ  ン  ト  一  覧
        - if @comments
          - @comments.each do |comment|
            .comments__text
              = link_to comment.user.nickname, "/users/#{comment.user_id}",class:"show-user"
              %p.comments__text--text 
                = comment.text 
                %br
                %i.far.fa-clock
                %time(datetime="#{comment.created_at}")= time_ago_in_words(comment.created_at)+"前"
    -# コメント説明
    .product-comment-form
      - if current_user
        = form_with model: [@product, @comment], class: "product-comment-form__new", local: true do |f|
          = f.text_area :text, class: "product-comment-form__new--text", plsceholder: "コメントする", rows: "2"
          %p.product-comment-form__new--report
            相手のことを考え丁寧なコメントを心がけましょう。
            %br
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = f.submit "コメントする",class: "product-comment-form__new--btn fas fa-star"
      - else
        %strong
          %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
    -# 別商品へのリンク
    .product-after-before
      .product-after-before__before
        ＜前の商品
      .product-after-before__after
        次の商品＞
    .product-show-category
      = link_to category_path(@product.category) do
        = @product.category.name
        商品をもっとみる

  -# フッター
  = render 'shared/footer'